In [135]:
import pandas as pd

In [136]:
titanic_df = pd.read_csv("titanic.csv")

In [137]:
df_from_url = pd.read_csv("https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv")

In [138]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [139]:
df_from_url.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [140]:
df_from_txt = pd.read_table("data_set.txt", sep="/t")

C:\Users\prane\AppData\Local\Temp\ipykernel_26900\501255945.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_from_txt = pd.read_table("data_set.txt", sep="/t")

In [141]:
df_from_txt.head()

  RollNo\tName\tClass\tSection\tMarks
0               101\tAarav\t10\tA\t88
1              102\tAnanya\t10\tA\t92
2               103\tRohan\t10\tB\t76
3               104\tPriya\t10\tB\t85
4              105\tVikram\t10\tA\t90

In [142]:
df_from_txt = pd.read_table("data_set.txt", sep="\t")

In [143]:
df_from_txt.head()

   RollNo    Name  Class Section  Marks
0     101   Aarav     10       A     88
1     102  Ananya     10       A     92
2     103   Rohan     10       B     76
3     104   Priya     10       B     85
4     105  Vikram     10       A     90

In [144]:
student_data = {
"Rool_No":[10,20,30,40,50],
"Name":["Praneeth", "Reddy", "Karthik", "Tharun", "Shiva"],
"Department":["IT", "CSE", "AIML", "DS", "CS"],
"Percentage":[100, 86, 200, 500, 100],
}

In [145]:
df_from_dict = pd.DataFrame(student_data)

In [146]:
df_from_dict.head()

   Rool_No      Name Department  Percentage
0       10  Praneeth         IT         100
1       20     Reddy        CSE          86
2       30   Karthik       AIML         200
3       40    Tharun         DS         500
4       50     Shiva         CS         100

In [147]:
df_from_json = pd.read_json("data.json")

In [148]:
df_from_json.head()

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [149]:
df_from_json.to_json(
    "student_data.json",
    orient = "records", 
    indent = 4
)

In [150]:
json_string_data = """
[{
"roll_no":124, 
"Name":"Praneeth",
"Marks":89
},
{
"roll_no":125,
"Name":"Karthik",
"Marks":74
},
{
"roll_no":111,
"Name":"Reddy",
"Marks":100
}]
"""
from io import StringIO
df_json_from_string = pd.read_json(StringIO(json_string_data))

In [151]:
df_json_from_string

   roll_no      Name  Marks
0      124  Praneeth     89
1      125   Karthik     74
2      111     Reddy    100

In [152]:
json_url = "https://jsonplaceholder.typicode.com/users"
df_json_from_url = pd.read_json(json_url)
df_json_from_url

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,"{'street': 'Norberto Crossing', 'suite': 'Apt....",1-477-935-8478 x6430,ola.org,"{'name': 'Considine-Lockman', 'catchPhrase': '..."
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,"{'street': 'Rex Trail', 'suite': 'Suite 280', ...",210.067.6132,elvis.io,"{'name': 'Johns Group', 'catchPhrase': 'Config..."
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,"{'street': 'Ellsworth Summit', 'suite': 'Suite...",586.493.6943 x140,jacynthe.com,"{'name': 'Abernathy Group', 'catchPhrase': 'Im..."
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,"{'street': 'Dayna Park', 'suite': 'Suite 449',...",(775)976-6794 x41206,conrad.com,"{'name': 'Yost and Sons', 'catchPhrase': 'Swit..."
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,"{'street': 'Kattie Turnpike', 'suite': 'Suite ...",024-648-3804,ambrose.net,"{'name': 'Hoeger LLC', 'catchPhrase': 'Central..."

In [153]:
import sys
print(sys.executable)
%pip install openpyxl

C:\Users\prane\AppData\Local\Programs\Python\Python313\python.exe
Requirement already satisfied: openpyxl in c:\users\prane\appdata\local\programs\python\python313\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\prane\appdata\local\programs\python\python313\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: C:\Users\prane\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

In [154]:

df = pd.DataFrame(student_data)
df.to_excel("student_data.xlsx", sheet_name = "Student Details", index=False)
df_from_excel = pd.read_excel("student_data.xlsx")

In [155]:
df_from_excel

   Rool_No      Name Department  Percentage
0       10  Praneeth         IT         100
1       20     Reddy        CSE          86
2       30   Karthik       AIML         200
3       40    Tharun         DS         500
4       50     Shiva         CS         100

In [156]:
df_read_from_excel = pd.read_excel("student_data.xlsx", sheet_name = "Student Details",)

In [157]:
df_read_from_excel

   Rool_No      Name Department  Percentage
0       10  Praneeth         IT         100
1       20     Reddy        CSE          86
2       30   Karthik       AIML         200
3       40    Tharun         DS         500
4       50     Shiva         CS         100

In [158]:
course_data = {
    "course_id" :["c101","c102","c103","c104"],
    "course_name" : ["Python", "Java", "ML", "DS"],
    "credits" : [4 , 3 , 4, 5]
}
cd = pd.DataFrame(course_data)

In [159]:
with pd.ExcelWriter("college_data.xlsx", engine = "openpyxl") as writer:
    df_from_excel.to_excel(
        writer, 
        sheet_name = "Students",
        index = False
    )
    cd.to_excel(
    writer, 
    sheet_name = "courses",
    index=False
    )

In [160]:
excel_data = pd.read_excel("college_data.xlsx", sheet_name = None)

In [161]:
print(excel_data.keys())

dict_keys(['Students', 'courses'])

In [162]:
excel_data["Students"]

   Rool_No      Name Department  Percentage
0       10  Praneeth         IT         100
1       20     Reddy        CSE          86
2       30   Karthik       AIML         200
3       40    Tharun         DS         500
4       50     Shiva         CS         100

In [163]:
excel_data["courses"]

  course_id course_name  credits
0      c101      Python        4
1      c102        Java        3
2      c103          ML        4
3      c104          DS        5